name: Auto UN Report

on:
  schedule:
    # Se ejecuta cada 24 horas
    - cron: '0 */24 * * *'
  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar Agente IA
        env:
          
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python main.py

      - name: Guardar cambios (Commit & Push)
        run: |
          git config --global user.name 'Forex-Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add index.html
          # El commit solo se hace si hubo cambios reales
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update: Nuevo reporte generado" && git push)